# app/telemetry/tracing.py
"""
OpenTelemetry tracing setup for the bookrec application.

Configures the global TracerProvider with an OTLP/HTTP exporter targeting
Jaeger and registers auto-instrumentors for FastAPI, httpx, and SQLAlchemy.

Call setup_tracing(app) once from the FastAPI lifespan before accepting
traffic. Call shutdown_tracing() in the lifespan teardown to flush buffered
spans cleanly on Gunicorn graceful restart.

Modules that need a tracer call opentelemetry.trace.get_tracer(__name__)
directly — they have no import dependency on this module.

Environment variables:
    OTEL_SDK_DISABLED           Set to "true" to disable all instrumentation.
                                The NoOp provider remains in place, making the
                                entire tracing path zero-cost. Useful in unit
                                tests that do not need traces.
    OTEL_EXPORTER_OTLP_ENDPOINT OTLP/HTTP endpoint for Jaeger. Defaults to
                                http://localhost:4318.
    OTEL_ENVIRONMENT            Deployment environment label attached to every
                                span as a resource attribute. Defaults to
                                "production". Set to "test" in test runs.
    TEST_RUN_ID                 Optional. When set, attached to every span as
                                a resource attribute so traces from a specific
                                test session can be isolated in Jaeger.
                                Auto-generated by the test conftest; absent in
                                production.
"""

from __future__ import annotations

import logging
import os

from fastapi import FastAPI
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

logger = logging.getLogger(__name__)

_SERVICE_NAME = "bookrec"
_EXCLUDED_URLS = "/health/live,/health/ready,/metrics"
_DEFAULT_OTLP_ENDPOINT = "http://localhost:4318"


def _instrument_sqlalchemy() -> None:
    """
    Instrument both SQLAlchemy engines with explicit engine references.

    Both engines are created at module level in app.database when the module
    is first imported — before the lifespan runs. The global instrument() call
    only patches create_engine going forward and would therefore miss them.
    Passing each engine explicitly attaches instrumentation to the already-
    created instances regardless of creation order.

    The async engine exposes its underlying sync engine via .sync_engine, which
    is what SQLAlchemyInstrumentor expects in both cases.

    Imported inside the function body to avoid a circular import: main.py
    imports tracing, main.py also imports app modules, so keeping this import
    lazy sidesteps any potential cycle at startup.
    """
    from app.database import async_engine, engine

    if engine is not None:
        SQLAlchemyInstrumentor().instrument(engine=engine)
    if async_engine is not None:
        SQLAlchemyInstrumentor().instrument(engine=async_engine.sync_engine)


def setup_tracing(app: FastAPI) -> None:
    """
    Configure the global TracerProvider and register auto-instrumentors.

    Should be called once at the start of the FastAPI lifespan, before any
    requests are accepted. The function is idempotent with respect to the
    auto-instrumentors — calling it a second time in the same process is safe
    but has no effect beyond replacing the global provider.

    Auto-instrumentation coverage:
      - FastAPI: every inbound request becomes a root span with HTTP method,
        route, and status code attributes.
      - httpx: every model server POST becomes a child span under the active
        request context, capturing round-trip time per server automatically.
      - SQLAlchemy: the read-books filter DB query becomes a child span with
        the SQL statement and execution time. Both the sync and async engines
        are instrumented explicitly by reference since they are created at
        module level before the lifespan runs.

    Resource attributes on every span:
      - service.name       always "bookrec"
      - deployment.environment  from OTEL_ENVIRONMENT, default "production"
      - test.run_id        from TEST_RUN_ID when present (test runs only)

    Args:
        app: The FastAPI application instance to instrument for inbound
             request tracing.
    """
    if os.getenv("OTEL_SDK_DISABLED", "").lower() == "true":
        logger.info("OpenTelemetry tracing disabled via OTEL_SDK_DISABLED=true")
        return

    resource_attributes = {
        "service.name": _SERVICE_NAME,
        "deployment.environment": os.getenv("OTEL_ENVIRONMENT", "production"),
    }

    run_id = os.getenv("TEST_RUN_ID")
    if run_id:
        resource_attributes["test.run_id"] = run_id

    resource = Resource.create(resource_attributes)
    provider = TracerProvider(resource=resource)

    otlp_endpoint = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", _DEFAULT_OTLP_ENDPOINT)
    exporter = OTLPSpanExporter(endpoint=otlp_endpoint)
    provider.add_span_processor(BatchSpanProcessor(exporter))

    trace.set_tracer_provider(provider)

    FastAPIInstrumentor.instrument_app(app, excluded_urls=_EXCLUDED_URLS)
    HTTPXClientInstrumentor().instrument()
    _instrument_sqlalchemy()

    logger.info(
        "OpenTelemetry tracing configured: environment=%s endpoint=%s run_id=%s",
        resource_attributes["deployment.environment"],
        otlp_endpoint,
        run_id or "n/a",
    )


def shutdown_tracing() -> None:
    """
    Flush buffered spans and shut down the active TracerProvider.

    Must be called from the FastAPI lifespan teardown to ensure all buffered
    spans are exported before the process exits. The BatchSpanProcessor
    flushes with a 30-second timeout so in-flight spans are not dropped on
    Gunicorn graceful restart or SIGTERM.

    Safe to call when tracing is disabled — the NoOp provider's shutdown is
    a no-op.
    """
    provider = trace.get_tracer_provider()
    if isinstance(provider, TracerProvider):
        provider.shutdown()
        logger.info("OpenTelemetry tracing shut down cleanly")
