# docker/spark-loader/docker-compose.yml
services:
  spark-loader:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-loader:local

    volumes:
      - ../..:/app:rw

    env_file:
      - /etc/bookrec.env

    # If using 127.0.0.1 in JDBC_URL with local MySQL:
    network_mode: "host"

    working_dir: /app

    # Make the JDBC driver visible to Spark
    environment:
      - PYSPARK_SUBMIT_ARGS=--driver-class-path /opt/jdbc/mysql-connector-j-8.4.0.jar --jars /opt/jdbc/mysql-connector-j-8.4.0.jar pyspark-shell

    command: >
      bash -lc "python /app/spark_apps/load_enrichment_to_sql.py"

