# docker/spark-loader/docker-compose.yml
services:
  spark-loader:
    image: apache/spark:3.4.0-python3
    
    volumes:
      - ../..:/app:rw

    env_file:
      - /etc/bookrec.env

    network_mode: "host"
    working_dir: /app
    
    environment:
      - PYTHONPATH=/tmp/python-libs
      - SPARK_LOCAL_DIRS=/tmp/spark-local
    
    command: >
      bash -c "
      pip install --target=/tmp/python-libs pymysql &&
      mkdir -p /tmp/.ivy2 &&
      /opt/spark/bin/spark-submit
      --conf spark.jars.ivy=/tmp/.ivy2
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0,com.mysql:mysql-connector-j:8.4.0
      /app/spark_apps/stream_enrichment_to_sql.py
      "
